// Copyright 2018 Bogatova Margarita

#ifndef  MODULES_PRIORITY_QUEUE_SRC_PRIORITY_QUEUE_CPP_
#define  MODULES_PRIORITY_QUEUE_SRC_PRIORITY_QUEUE_CPP_

#endif  // MODULES_PRIORITY_QUEUE_SRC_PRIORITY_QUEUE_CPP_
